language: generic
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
  - os: osx
    osx_image: xcode10.2
    language: c++
    compiler: clang
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc; sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++; gcc -v; fi
script:
  - set -e
  - |
    git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
    [[ "${TRAVIS_OS_NAME}" == "osx" ]]   && make bsd -C maiken CXX=clang++ && export MKN_LIB_LINK_LIB=1
    [[ "${TRAVIS_OS_NAME}" == "linux" ]] && make nix -C maiken
    mv maiken/mkn .
    ./mkn build -dtOSp test run -a "-fPIC -O2 -std=c++14"
