version: 0.1.{build}
max_jobs: 1
image:
- Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2
platform: x64
configuration: Release
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  touch Makefile
  touch make.bat
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  - SET MKN_CL_PREFERRED=1
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; mkn build -dtOKp test -a -EHsc run"
